//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIX.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAbsence
    {
        public int absenceId { get; set; }
        public System.DateTime firstDay { get; set; }
        public System.DateTime lastDay { get; set; }
        public string reason { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> staffId { get; set; }
    
        public virtual tblStaff tblStaff { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
