//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIX.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAbsence
    {
        public string fullname { get; set; }
        public string username { get; set; }
        public int floorNumber { get; set; }
        public string engagement { get; set; }
        public System.DateTime firstDay { get; set; }
        public System.DateTime lastDay { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
    }
}
