//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLIX.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStaff
    {
        public string fullname { get; set; }
        public string username { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int floorNumber { get; set; }
        public string engagement { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string name { get; set; }
    }
}
